# Generated by Django 2.0 on 2022-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='job_id',
            field=models.ManyToManyField(to='job.JobModel'),
        ),
    ]
