# Generated by Django 2.0 on 2022-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_departmentmodel_expected_employees'),
        ('contract', '0003_auto_20220809_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='job_id',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='department_id',
            field=models.ManyToManyField(to='department.DepartmentModel'),
        ),
    ]
