# Generated by Django 2.0 on 2022-08-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_departmentmodel_expected_employees'),
        ('contract', '0004_auto_20220814_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='department_id',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='department_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentModel'),
        ),
    ]
