# Generated by Django 2.0 on 2022-08-07 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=40)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
                ('education', models.CharField(max_length=500)),
                ('skill', models.CharField(max_length=500)),
                ('experience', models.CharField(max_length=500)),
                ('objective', models.CharField(max_length=500)),
                ('interest', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=15)),
            ],
        ),
    ]
