# Generated by Django 2.0 on 2022-08-08 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 8, 8, 13, 40, 18, 667674, tzinfo=utc), verbose_name='Birthday'),
        ),
    ]
