# Generated by Django 2.0 on 2022-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20220808_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='education',
            field=models.CharField(default='(2001-2005)Bachelor of Technology(electronic)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='experience',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='skill',
            field=models.CharField(default='HTML5, CSS3, Javascript', max_length=500),
        ),
    ]
