# Generated by Django 4.1.3 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20220809_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='education',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recruitmentmodel',
            name='skill',
            field=models.CharField(max_length=500),
        ),
    ]
