# Generated by Django 2.0 on 2022-07-06 16:08

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='emp492', max_length=70)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('birthday', models.DateField(default=datetime.datetime(2022, 7, 6, 16, 8, 5, 537548, tzinfo=utc), verbose_name='Birthday')),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=125, verbose_name='Email')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs/')),
                ('salary', models.CharField(default='00,000.00', max_length=16)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
