# Generated by Django 2.0 on 2022-08-10 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '__first__'),
        ('contract', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='emp420', max_length=70)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=125, verbose_name='Email')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='imgs/')),
                ('salary', models.CharField(default='00,000.00', max_length=16)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contract.ContractModel')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentModel')),
            ],
        ),
    ]
