# Generated by Django 2.0 on 2022-07-08 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20220707_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='contract_id',
            new_name='contract_name',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 13, 26, 1, 858246, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp596', max_length=70),
        ),
    ]
