# Generated by Django 2.0 on 2022-07-08 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20220708_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='contract_name',
            new_name='contract',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 13, 31, 52, 517911, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp620', max_length=70),
        ),
    ]
