# Generated by Django 2.0 on 2022-07-08 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20220707_2039'),
        ('employee', '0013_auto_20220708_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentModel'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 19, 30, 50, 924109, tzinfo=utc), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp946', max_length=70),
        ),
    ]
