# Generated by Django 2.0 on 2022-07-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20220720_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp960', max_length=70),
        ),
    ]
