# Generated by Django 2.2.13 on 2022-07-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_auto_20220727_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp283', max_length=70),
        ),
    ]
