# Generated by Django 2.0 on 2022-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_auto_20220727_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp214', max_length=70),
        ),
    ]
