# Generated by Django 2.0 on 2022-07-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_auto_20220731_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp590', max_length=70),
        ),
    ]
