# Generated by Django 2.0 on 2022-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_auto_20220731_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp117', max_length=70),
        ),
    ]
