# Generated by Django 2.0 on 2022-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_auto_20220731_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp275', max_length=70),
        ),
    ]
