# Generated by Django 2.0 on 2022-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_auto_20220801_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp679', max_length=70),
        ),
    ]
