# Generated by Django 2.0 on 2022-07-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_auto_20220801_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp318', max_length=70),
        ),
    ]
