# Generated by Django 2.0 on 2022-07-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_auto_20220801_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp165', max_length=70),
        ),
    ]
