# Generated by Django 2.0 on 2022-08-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_auto_20220807_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp271', max_length=70),
        ),
    ]
