# Generated by Django 2.0 on 2022-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_auto_20220808_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp880', max_length=70),
        ),
    ]
