# Generated by Django 4.1.3 on 2022-11-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_auto_20220809_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.CharField(default='emp982', max_length=70),
        ),
    ]
