# Generated by Django 2.0 on 2022-08-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensemodel',
            old_name='status',
            new_name='cash_out',
        ),
    ]
