# Generated by Django 2.0 on 2022-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='history',
            field=models.TextField(default='No History', max_length=1000, verbose_name='History'),
        ),
    ]
