# Generated by Django 2.0 on 2022-07-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='DepartmentModel',
        ),
    ]
