# Generated by Django 2.0 on 2022-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20220707_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='expected_employees',
            field=models.IntegerField(default=0, verbose_name='Expected Employees'),
        ),
    ]
